
logging:
  level:
    root: info
    com.leo: debug
  file:
    name: devlog/debug.log
  pattern:
#    console: '%d{HH:mm:ss.SSS} %contextName [%thread] %-5level %logger{36} - %msg %n'
#  config: classpath:logbak-spring.xml

